[package]
name = "actix-petstore"
version = "0.1.0"
authors = ["boxdot <d@zerovolt.org>"]
edition = "2018"

[dependencies]
actix = "0.7"
actix-web = { git = "https://github.com/boxdot/actix-web", rev = "9814de0f" }
env_logger = "0.6"
serde = { version = "1.0", features = ["derive"] }
